import re

filepath = "WOS_State_Collector_V3_34_6_Correlation_Authority_Split.py"
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    "▶ Démarrer capture": "▶ Start capture",
    "■ Arrêter": "■ Stop",
    "Collecte": "Collection",
    "Données / Exports": "Data / Exports",
    "Analyser PCAPNG": "Analyze PCAPNG",
    "Exporter joueurs CSV": "Export Players CSV",
    "Exporter refresh queue": "Export Refresh Queue",
    "Journal": "Log",
    "Prêt.": "Ready.",
    "Capture en cours →": "Capture in progress →",
    "Capture LIVE démarrée. Ouvre WOS puis une liste d'alliance.": "LIVE Capture started. Open WOS then an alliance list.",
    "Capture arrêtée.": "Capture stopped.",
    "Capture arrêtée et session enregistrée.": "Capture stopped and session saved.",
    "Session / Base": "Session / Database",
    '("Blocs","blocks")': '("Blocks","blocks")',
    '("Décodés","decoded")': '("Decoded","decoded")',
    '("Joueurs","players")': '("Players","players")',
    '("Complets","complete")': '("Complete","complete")',
    '("Alliances découvertes","alliance_discovered")': '("Discovered Alliances","alliance_discovered")',
    '("Découverte","discovered")': '("Discovery","discovered")',
    '("Résolus","resolved")': '("Resolved","resolved")',
    "en attente de trafic client...": "waiting for client traffic...",
    "dernier=": "last=",
    "prochain=": "next=",
    "famille=": "family=",
    "trames=": "frames=",
    "détection...": "detecting...",
    "Choisir capture": "Choose capture",
    "Tous": "All",
    "Analyse offline :": "Offline analysis :",
    "Analyse offline terminée.": "Offline analysis finished.",
    "Erreur offline: ": "Offline error: ",
    "Export : ": "Export : ",
    "CSV exporté : ": "CSV exported : ",
    "File refresh : ": "Refresh queue : ",
    "File refresh exportée : ": "Refresh queue exported : ",
    "Aucune cible pending dans le roster courant.": "No pending target in the current roster.",
    "Choisir un joueur": "Choose a player",
    "Recherche :": "Search :",
    '"Toutes"': '"All"',
    '"Pseudo"': '"Nickname"',
    '"Raison"': '"Reason"',
    "Sélectionne un joueur puis double-clique, ou clique sur Armer.": "Select a player then double-click, or click on Arm.",
    "Annuler": "Cancel",
    "Armer la cible": "Arm target",
    "Active Lab arme : ": "Active Lab armed : ",
    "Active Lab exporte : ": "Active Lab exported : ",
    "ERREUR ouverture : ": "ERROR opening : ",
    "Impossible d'ouvrir la liste :\\n": "Unable to open the list:\\n",
    "Aucun roster courant disponible.": "No current roster available.",
    "Choisir 5 joueurs": "Choose 5 players",
    "Ordre du test": "Test order",
    "Choisis exactement 5 joueurs.": "Choose exactly 5 players.",
    "Sequence Lab : ouvre ": "Sequence Lab : open ",
    "Ajouter →": "Add →",
    "Retirer": "Remove",
    '"Demarrer"': '"Start"',
    "Sequence Lab arrete.": "Sequence Lab stopped.",
    "Sequence Lab exporte : ": "Sequence Lab exported : ",
    "ouvre 5 fois ": "open 5 times ",
    "Counter Lab arrêté.": "Counter Lab stopped.",
    "Choisis UN joueur et ouvre/ferme son profil 5 fois.": "Choose ONE player and open/close their profile 5 times.",
    "Démarrer x5": "Start x5",
    "Raw Counter Builder - Choisir une cible": "Raw Counter Builder - Choose a target",
    "compteur prédit": "predicted counter",
    "attente du vrai 7D02": "waiting for real 7D02",
    "Raw Builder armé : ": "Raw Builder armed : ",
    "Après Armer : ouvre immédiatement ce profil dans WOS, sans autre action.": "After Arming : open this profile immediately in WOS, with no other action.",
    "Construire / Armer": "Build / Arm",
    "Request Builder exporté : ": "Request Builder exported : ",
    "Counter Tracker exporté : ": "Counter Tracker exported : ",
    "Arme, ouvre ce profil UNE fois, attends 5 s, puis Stop Raw.": "Arm, open this profile ONCE, wait 5s, then Stop Raw.",
    "Raw Diagnostic terminé : ": "Raw Diagnostic finished : ",
    "Raw Diagnostic exporté : ": "Raw Diagnostic exported : ",
    "Raw Counter exporté : ": "Raw Counter exported : ",
    "Couverture Alliances / État": "Alliance / State Coverage",
    "Rosters vus:": "Rosters seen:",
    "Rosters complets:": "Complete rosters:",
    "Membres capturés:": "Captured members:",
    "Profils résolus:": "Resolved profiles:",
    "Filtre:": "Filter:",
    '"Annoncé"': '"Announced"',
    '"Capturés"': '"Captured"',
    "Dernier roster": "Last roster",
    "Couverture alliances exportée : ": "Alliance coverage exported : ",
    "Découverte alliances exportée : ": "Alliance discovery exported : ",
    "Découverte État exportée : ": "State discovery exported : ",
    "Capture impossible": "Capture impossible",
    "Armer": "Arm",
    "1050x720": "1100x750",
    "850x560": "900x580",
}

for fr, en in replacements.items():
    content = content.replace(fr, en)

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)

print("Translation script completed.")
